// Profile
export const GET_ACCOUNT = "GET_ACCOUNT";
export const RESET_PROFILE = "RESET_PROFILE";

// Auth
export const CHECK_AUTHENTICATION = "CHECK_AUTHENTICATION";
export const UPDATE_REFRESHING = "UPDATE_REFRESHING";
export const LOGOUT = "LOGOUT";
export const LOGIN = "LOGIN";

// Courses
export const CURRENT_COURSE = "CURRENT_COURSE";
export const FETCH_COURSES = "FETCH_COURSES";
export const APPEND_COURSES = "APPEND_COURSES";
export const RESET_COURSES = "RESET_COURSES";
export const FETCH_ALL_COURSES = "FETCH_ALL_COURSES";
export const COURSE_QUERY = "COURSE_QUERY";

// Activities
export const FETCH_ACTIVITIES = "FETCH_ACTIVITIES";
export const APPEND_ACTIVITIES = "APPEND_ACTIVITIES";
export const RESET_ACTIVITIES = "RESET_ACTIVITIES";
export const FETCH_ALL_ACTIVITIES = "FETCH_ALL_ACTIVITIES";
export const ACTIVITY_QUERY = "ACTIVITY_QUERY";
export const UPDATE_ACTIVITY = "UPDATE_ACTIVITY";
export const FETCH_SEARCH_RESULTS = "FETCH_SEARCH_RESULTS";
export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";

// Students
export const CURRENT_STUDENT = "CURRENT_STUDENT";
export const FETCH_STUDENTS = "FETCH_STUDENTS";
export const APPEND_STUDENTS = "APPEND_STUDENTS";
export const RESET_STUDENTS = "RESET_STUDENTS";
export const FETCH_ALL_STUDENTS = "FETCH_ALL_STUDENTS";
export const STUDENT_QUERY = "COURSE_QUERY";
export const REMOVE_STUDENT = "REMOVE_STUDENT";

export const FETCH_ALL_BOOKMARKS = "FETCH_ALL_BOOKMARKS";

// Announcements
export const FETCH_ANNOUNCEMENTS = "FETCH_ANNOUNCEMENTS";
export const APPEND_ANNOUNCEMENTS = "APPEND_ANNOUNCEMENTS";
export const RESET_ANNOUNCEMENTS = "RESET_ANNOUNCEMENTS";
export const FETCH_ALL_ANNOUNCEMENTS = "FETCH_ALL_ANNOUNCEMENTS";
export const ANNOUNCEMENT_QUERY = "ANNOUNCEMENT_QUERY";
export const UPDATE_ANNOUNCEMENT = "UPDATE_ANNOUNCEMENT";


// Quizzes
export const FETCH_QUIZZES = "FETCH_QUIZZES";
export const APPEND_QUIZZES = "APPEND_QUIZZES";
export const RESET_QUIZZES = "RESET_QUIZZES";
export const FETCH_ALL_QUIZZES = "FETCH_ALL_QUIZZES";
export const QUIZ_QUERY = "QUIZ_QUERY";
export const UPDATE_QUIZ = "UPDATE_QUIZ";
export const QUIZ_FETCH_SEARCH_RESULTS = "QUIZ_FETCH_SEARCH_RESULTS";
export const QUIZ_SET_SEARCH_TEXT = "QUIZ_SET_SEARCH_TEXT";
export const FETCH_ALL_QUIZ_QUESTIONS = "FETCH_ALL_QUIZ_QUESTIONS";